kind: pipeline
name: default

steps:
  - name: mariadb
    image: mariadb
    commands:
      - sleep 40
      - mysql -u admin -h database -padmin --execute="SELECT VERSION();"

  - name: build
    image: golang
    ports: [ 80 ]
    group: parallel-1
    commands:
      - CGO_ENABLED=0 go build -o build/bm-inventory cmd/main.go
      - ./build/bm-inventory &
      - sleep 60
      - go test -v ./subsystem/... -count=1 -ginkgo.skip=drone_disable -ginkgo.v
    environment:
      INVENTORY: build:8090
      DB_HOST: database
      DB_PORT: 3306
      TEST_MODE: true
    volumes:
      - name: mounted
        path: /var/run/docker.sock

services:
  - name: database
    image: mariadb
    group: parallel-1
    environment:
      MYSQL_DATABASE: installer
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_RANDOM_ROOT_PASSWORD: admin

  - name: scality
    image: scality/s3server