kind: ServiceAccount
apiVersion: v1
metadata:
  name: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - pods
      - endpoints
      - services
  - verbs:
      - get
      - watch
      - list
      - delete
      - create
    apiGroups:
      - batch
    resources:
      - jobs
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default
