name: unit-test workflow

on:
  [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7.17
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo pip install strato-skipper
        mkdir -p ~/.docker
        echo "{}" > ~/.docker/config.json
        touch ${HOME}/.gitconfig
    - name: go build
      run: |
        skipper make build unit-test
